# Generated by Django 4.0.6 on 2022-07-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tunnel',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
    ]
