# Generated by Django 4.0.6 on 2022-07-07 19:19

from django.db import migrations, models
import tunnel_monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_monitor', '0002_rename_auth_user_id_tunnel_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='lower_bound',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[tunnel_monitor.models.validate_currency]),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='upper_bound',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[tunnel_monitor.models.validate_currency]),
        ),
    ]
