# Generated by Django 4.0.6 on 2022-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_monitor', '0003_alter_tunnel_lower_bound_alter_tunnel_upper_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='interval',
            field=models.IntegerField(choices=[(1, '1 minute'), (5, '5 minutes'), (15, '15 minutes'), (60, '1 hour'), (1440, '1 day')], default=15),
        ),
    ]
