# Generated by Django 4.0.6 on 2022-07-07 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tunnel_monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_monitor', '0004_alter_tunnel_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[tunnel_monitor.models.validate_currency])),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunnel_monitor.tunnel')),
            ],
        ),
    ]
