# Generated by Django 4.0.6 on 2022-07-08 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_monitor', '0005_pricelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelog',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
